export type PrinterType = {
  MFDModel: string
  resource: number,
  fillingOutSheet: number,

  partNumberCartridge: string,
  resourceCartridge: number,
  priceCartridge: number,
  partNumberCartridge2: string,
  resourceCartridge2: number,
  priceCartridge2: number,
  checkboxCartridge: boolean,

  partNumberPaperFeedUnit1: string,
  resourcePaperFeedUnit1: number,
  pricePaperFeedUnit1: number,
  partNumberPaperFeedUnit2: string,
  resourcePaperFeedUnit2: number,
  pricePaperFeedUnit2: number,
  partNumberPaperFeedUnit3: string,
  resourcePaperFeedUnit3: number,
  pricePaperFeedUnit3: number,

  partNumberADFNode1: string
  resourceADFNode1: number,
  priceADFNode1: number,
  partNumberADFNode2: string,
  resourceADFNode2: number,
  priceADFNode2: number,
  partNumberADFNode3: string,
  resourceADFNode3: number,
  priceADFNode3: number,

  partNumberPhotoreceptorUnit1: string,
  resourcePhotoreceptorUnit1: number,
  pricePhotoreceptorUnit1: number,
  partNumberPhotoreceptorUnit2: string,
  resourcePhotoreceptorUnit2: number,
  pricePhotoreceptorUnit2: number,
  partNumberPhotoreceptorUnit3: string,
  resourcePhotoreceptorUnit3: number,
  pricePhotoreceptorUnit3: number,
  partNumberPhotoreceptorUnit4: string,
  resourcePhotoreceptorUnit4: number,
  pricePhotoreceptorUnit4: number,
  partNumberPhotoreceptorUnitFull: string,
  resourcePhotoreceptorUnitFull: number,
  pricePhotoreceptorUnitFull: number,
  checkboxPhotoreceptorUnit: boolean,

  partNumberDevelopmentBlock1: string,
  resourceDevelopmentBlock1: number,
  priceDevelopmentBlock1: number,
  partNumberDevelopmentBlock2: string,
  resourceDevelopmentBlock2: number,
  priceDevelopmentBlock2: number,
  partNumberDevelopmentBlock3: string,
  resourceDevelopmentBlock3: number,
  priceDevelopmentBlock3: number,
  partNumberDevelopmentBlock4: string,
  resourceDevelopmentBlock4: number,
  priceDevelopmentBlock4: number,
  partNumberDevelopmentBlockFull: string,
  resourceDevelopmentBlockFull: number,
  priceDevelopmentBlockFull: number,
  checkboxDevelopmentBlock: boolean,

  partNumberPinningUnit1: string,
  resourcePinningUnit1: number,
  pricePinningUnit1: number,
  partNumberPinningUnit2: string,
  resourcePinningUnit2: number,
  pricePinningUnit2: number,
  partNumberPinningUnit3: string,
  resourcePinningUnit3: number,
  pricePinningUnit3: number,
  partNumberPinningUnit4: string,
  resourcePinningUnit4: number,
  pricePinningUnit4: number,
  partNumberPinningUnit5: string,
  resourcePinningUnit5: number,
  pricePinningUnit5: number,
  partNumberPinningUnit6: string,
  resourcePinningUnit6: number,
  pricePinningUnit6: number,
  partNumberPinningUnitFull: string,
  resourcePinningUnitFull: number,
  pricePinningUnitFull: number,
  checkboxPinningUnit: boolean,
}
export type ResponsePrinterType = {
  id: string
  fields: PrinterType
}
